/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카카오 OAuth 콜백. httpOnly 쿠키 발급 (13절 "토큰을 프론트에 두지 않는다") */
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그인 성공 시 진입점으로 리다이렉트 */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인 사용자 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 탈퇴. 연결된 사유·반응 기록도 함께 삭제 (12절) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 탈퇴 처리됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 지도 생성. 생성 시 seeding 잡을 트리거한다 (architecture.md 3절) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MapCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Map"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지도 상세 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Map"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 초대 링크 발급 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invite"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 초대 수락. 로그인 전 접근 시 처리 방식은 결정 이슈 미결 (#15 분리분) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Map"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 구성원 목록 (color, online) — 5절 "구성원 배지 + 목록" */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 핀 목록. 보는 사람 기준 필터링 — visibility=private인 남의 후보는 내려주지 않는다 (5-5-1) */
        get: {
            parameters: {
                query?: {
                    category?: components["schemas"]["Category"];
                    kind?: components["schemas"]["PinKind"];
                };
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pin"][];
                    };
                };
            };
        };
        put?: never;
        /** 핀 생성 (링크·검색·좌표 3경로, 5-9의 대량 버전은 v2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PinCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pin"];
                    };
                };
                409: components["responses"]["PinDuplicate"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 분류 × 종류 이중 필터 집계 (기획안 4절). 이슈 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilterCounts"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pins/{pinId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 핀 삭제. 권한 규정은 결정 이슈 미결 (#15 분리분) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pinId: components["parameters"]["PinId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pins/{pinId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 반응 등록/수정. 반대(against)는 reason 필수 (가드레일 3) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pinId: components["parameters"]["PinId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReactionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reaction"];
                    };
                };
                422: components["responses"]["EvidenceRequired"];
            };
        };
        post?: never;
        /** 핀 되돌리기 — 구성원 누구나 가능 (15-1) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pinId: components["parameters"]["PinId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 반응 취소됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/recommend/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리별 추천 버튼 활성화 판정 (5-4) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["Readiness"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** run 생성 — 근거 조립 시작 (①②) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        category: components["schemas"]["Category"];
                    };
                };
            };
            responses: {
                /** @description run 생성됨, 근거 조립 진행 중 (SSE run.progress로 진행 상태 전달) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendRun"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 근거 리스트 조회 (5-5) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceLine"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 근거 토글('-') / 직접 추가('+') (5-5). '-'는 author 본인만 (permissions.md) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EvidencePatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceLine"][];
                    };
                };
            };
        };
        trace?: never;
    };
    "/runs/{runId}/regions/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지역 확인 (5-6-1). 사람이 쓴 반경 사유끼리 안 겹칠 때만 호출된다.
         *     signature가 이전과 같으면 재확인 없이 즉시 200. signature 변경(사유 수정/추가로 겹침 여부가 바뀜) 시에만 REGION_CONFLICT로 재확인 요구.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 두 지역 각각 찾기 선택 시 true */
                        accept_union?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Region"][];
                    };
                };
                409: components["responses"]["RegionConflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 「이대로 추천 받기」 — 실격 필터 + 선호 순위 실행 (③-a-2, ③-b, ④) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 실행 시작. 완료는 SSE run.progress(개인 채널) 또는 GET /runs/{id}/result 폴링 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendRun"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 추천 결과 조회 (funnel, regions, candidates) — 5-6 깔때기 표시 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendResult"];
                    };
                };
                404: components["responses"]["NoResults"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/widen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 반경 넓히기. 기본값 원만 확대한다 — 사람이 명시한 원(예 "숙소 기준 20분")은 자동으로 넓히지 않는다 (가드레일 4, 5-6-1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 재실행 시작 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 「다시 추천 받기」. 현재 뜬 대안 전체를 제외목록에 넣고 새로 찾는다 (3절, 루프가 닫힌다).
         *     3회 상한 초과 시 429 RETRY_LIMIT. 상한의 집계 단위는 결정 이슈 미결 — 응답의 attempt_no로 우선 노출.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    runId: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendRun"];
                    };
                };
                429: components["responses"]["RetryLimit"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidateId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 「지도에 올리기」 — 비공개 후보를 전체 채널에 공개, 핀으로 전환 (5-5-1, 가드레일 1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    candidateId: components["parameters"]["CandidateId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pin"];
                    };
                };
                404: components["responses"]["AiPinPrivate"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 확정 리스트 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShortlistItem"][];
                    };
                };
            };
        };
        put?: never;
        /** 확정 추가 — 구성원 누구나 (5-3, 15-1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        pin_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShortlistItem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shortlist/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 확정 제외 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 제외됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{mapId}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 동선 보기 (5-10). 순수 계산, 모델 미사용. 확정 핀이 여러 지역에 걸치면 지역별로 여러 동선을 반환한다.
         *     확정 리스트가 바뀌면 즉시 재계산 — 별도 재계산 요청 API 없음.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mapId: components["parameters"]["MapId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 공통 에러 포맷. 코드 카탈로그는 docs/errors.md */
        Error: {
            /** @example PIN_DUPLICATE */
            code: string;
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        Category: "음식점" | "카페" | "숙소" | "관광지";
        /**
         * @description 핀 종류는 이 3가지뿐 (기획안 9절). 확정이 나머지 둘을 덮어쓴다.
         * @enum {string}
         */
        PinKind: "일반" | "AI추천" | "확정";
        /** @description 요청자 기준 계산된 권한. FE는 이 값만 보고 버튼을 그린다 (permissions.md) */
        Permissions: {
            can_react?: boolean;
            can_revert?: boolean;
            can_add_to_shortlist?: boolean;
            can_remove_from_shortlist?: boolean;
            /** @description evidence_line 전용: 자기가 쓴 것만 true */
            can_disable?: boolean;
            can_delete?: boolean;
        };
        User: {
            id?: string;
            display_name?: string;
        };
        Map: {
            id?: string;
            title?: string;
            member_count?: number;
            confirmed_count?: number;
        };
        Invite: {
            token?: string;
            url?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        Member: {
            user_id?: string;
            display_name?: string;
            /** @description 구성원 색 팔레트·배정 주체는 결정 이슈 미결 */
            color?: string;
            online?: boolean;
        };
        MapCreateRequest: {
            title: string;
            /** @description 지도 생성 입력값 필드 확정 전 임시 */
            region_hint?: string;
        };
        PinCreateRequest: {
            category: components["schemas"]["Category"];
            /** @enum {string} */
            source?: "link" | "search" | "coordinate";
            link_url?: string;
            place_id?: string;
            lat?: number;
            lng?: number;
        };
        /**
         * @description docs/constraints.md 차원 압축 결과. 원본 가격 숫자는 API로 노출하지 않는다
         * @enum {string}
         */
        PriceBucket: "low" | "mid" | "high";
        /** @enum {string} */
        LabelConfidence: "known" | "unknown";
        /** @description 가드레일 5 "조건별 충족 체크" */
        Check: {
            fact_key?: string;
            label?: string;
            passed?: boolean;
            confidence?: components["schemas"]["LabelConfidence"];
            /** @description unknown_policy=pass+needs_check인 취향 조건이 unknown일 때 true */
            needs_check?: boolean;
        };
        Pin: {
            id?: string;
            map_id?: string;
            category?: components["schemas"]["Category"];
            kind?: components["schemas"]["PinKind"];
            /** @enum {string} */
            visibility?: "public" | "private";
            lat?: number;
            lng?: number;
            place_name?: string;
            price_bucket?: components["schemas"]["PriceBucket"];
            /** @description 게시된 AI 추천 핀도 상세에서 계속 노출한다 (가드레일 5) */
            checks?: components["schemas"]["Check"][];
            source_run_id?: string | null;
            reaction_summary?: {
                like?: number;
                neutral?: number;
                against?: number;
            };
            permissions?: components["schemas"]["Permissions"];
        };
        ReactionRequest: {
            /** @enum {string} */
            type: "like" | "neutral" | "against";
            reason_text?: string;
            reason_chip_ids?: string[];
        };
        Reaction: {
            pin_id?: string;
            user_id?: string;
            /** @enum {string} */
            type?: "like" | "neutral" | "against";
            reason_text?: string;
        };
        FilterCounts: {
            by_category?: {
                [key: string]: number;
            };
            by_kind?: {
                [key: string]: number;
            };
        };
        Readiness: {
            ready?: boolean;
            answered_count?: number;
            /** @description ceil(N/2). N의 정의는 결정 이슈 미결 */
            required_count?: number;
        };
        EvidenceLine: {
            id?: string;
            author_id?: string;
            author_display_name?: string;
            text?: string;
            /**
             * @description 꼭/선호/참고 (5-5)
             * @enum {string}
             */
            badge?: "required" | "preferred" | "reference";
            fact_key?: string | null;
            is_active?: boolean;
            permissions?: components["schemas"]["Permissions"];
        };
        EvidencePatchRequest: {
            toggle?: {
                id?: string;
                is_active?: boolean;
            }[];
            add?: {
                text?: string;
            }[];
        };
        Region: {
            id?: string;
            label?: string;
            signature?: string;
            confirmed?: boolean;
        };
        RecommendRun: {
            id?: string;
            map_id?: string;
            category?: components["schemas"]["Category"];
            /** @enum {string} */
            status?: "collecting_evidence" | "awaiting_region_confirm" | "executing" | "done" | "failed";
            attempt_no?: number;
        };
        Candidate: {
            id?: string;
            place_name?: string;
            /** @description 5-6-1 지역별 안배 태그 */
            region_label?: string;
            rank?: number;
            checks?: components["schemas"]["Check"][];
            /** @enum {string} */
            visibility?: "private" | "published";
            published_pin_id?: string | null;
        };
        RecommendResult: {
            run_id?: string;
            /** @description 5-6 깔때기 표 */
            funnel?: {
                label?: string;
                removed_count?: number;
            }[];
            regions?: components["schemas"]["Region"][];
            candidates?: components["schemas"]["Candidate"][];
        };
        ShortlistItem: {
            id?: string;
            pin?: components["schemas"]["Pin"];
            visit_order?: number | null;
            added_by?: string;
            permissions?: components["schemas"]["Permissions"];
        };
        Route: {
            region_label?: string;
            ordered_pin_ids?: string[];
            total_distance_m?: number;
            legs?: {
                from_pin_id?: string;
                to_pin_id?: string;
                distance_m?: number;
                approx_minutes?: number;
            }[];
        };
    };
    responses: {
        /** @description 인증 실패 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 이미 지도에 있는 장소 (가드레일 6) */
        PinDuplicate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 반대 반응에 사유가 없음 (가드레일 3) */
        EvidenceRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 필터 통과 후보 0개 (6절 "결과 0개") */
        NoResults: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 재시도 3회 초과 (6절 "재시도 3회 초과") */
        RetryLimit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 두 반경 사유가 겹치지 않음 — 사용자 확인 필요 (5-6-1) */
        RegionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 비공개 AI 후보에 요청자 본인이 아닌 사람이 접근 (5절 "비공개 AI 핀 접근 시 안내") */
        AiPinPrivate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        MapId: string;
        PinId: string;
        RunId: string;
        CandidateId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
